export const options = {
  WORKING_STATUS: {
    NOT_STARTED: "not_started",
    STARTED: "started",
    HOLD: "hold",
    SHUT_DOWN: "shut_down",
  },
  errorMessage: {
    SERVER_ERROR: "Oops! something went wrong.",
    INCORRECT_DATA: (data) => `The ${data} entered is incorrect`,
    INVALID_REQUEST: "Invalid Request",
    ROLE_INVALID_LOGIN: "Account access denied",
    DOES_NOT_EXIST: (data) => `The ${data} does not exist`,
    ALREADY_EXIST: (data) => `The ${data} already exist`,
    INCORRECT_FILE_DATA: "File contains invalid data",
    DATA_NOT_FOUND: (data) => `${data} not found`,
  },
  successMessage: {
    LOG: (data) => `You have ${data} successfully`,
    UPDATE_SUCCESS_MESSAGE: (data) => `${data} updated successfully`,
    DELETE_SUCCESS_MESSAGE: (data) => `${data} deleted successfully`,
    REMOVED_SUCCESS_MESSAGE: (data) => `${data} removed successfully`,
    ADD_SUCCESS_MESSAGE: (data) => `${data} added successfully`,
    SAVED_SUCCESS_MESSAGE: (data) => `${data} saved successfully`,
    CHANGED_SUCCESS_MESSAGE: (data) => `${data} changed successfully`,
  },
  messageStatus: {
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
  },
  defaultStatus: {
    ON_BOARDED: "on_boarded",
    PENDING: "pending",
    APPROVED: "approved",
    ACTIVE: "active",
    INACTIVE: "inactive",
    BLOCKED: "blocked",
    UNBLOCKED: "unblocked",
    DELETED: "deleted",
    DISAPPROVED: "disapproved",
    REJECTED: "rejected",
    WITHDRAWN: "withdrawn",
    COMPLETED: "completed",
  },
};
